spring.application.name=taskapi

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/taskdb
spring.datasource.username=postgres
spring.datasource.password=11111

# MongoDB Configuration (NEW - add this!)
spring.data.mongodb.uri=mongodb+srv://admin:admin123@cluster0.dj3tgtt.mongodb.net/notesdb?retryWrites=true&w=majority

# Server Configuration
server.port=8080

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true